### ISSUE TITLE
Add BEAT-19 Data

### ISSUE THREAD

**Issue by isaacmg** [CoronaWhy/task-ts#45]
We would like to incorporate the BEAT-19 data into our models. 

Acceptance Criteria 
- [ ] Code to join in BEAT19 Data incorporated into data crawler.
- [ ] Appropiate unit test coverage
- [ ] Code committed on GitHub with passing unit tests.

**Comment by antonpolishko** [comment]
Looks like this was already addressed. Check #56 and `task-ts/notebooks/beat19_EDA.ipynb`
