### ISSUE TITLE
Create cloud function to save county CSV to bucket

### ISSUE THREAD

**Issue by isaacmg** [CoronaWhy/task-ts#61]
- [ ] Deploy cloud function on GCS and test on incoming data.

**Comment by efawe** [comment]
Do we have a county csv already or do we need to aggregate one ?

**Comment by isaacmg** [comment]
So @efawe the main thing for this is to just create a cloud function to split up the data that you persisted in #48 into . This is currently already done in notebooks but in order to clean up notebooks and have unified county data having separate csv for each county would be useful. Also when we go to deploy the models to production in #60 we will need data persisted on a county level.

**Comment by isaacmg** [comment]
So just modify this function to output a CSV file in the format `task_ts/date/county_name.csv` to the proper path (I.e. https://github.com/CoronaWhy/task-ts/blob/23a77bf62de9ff7552b4be07b90ce58833a99ec2/corona_ts/data_utils/data_creator.py#L4

**Comment by efawe** [comment]
Figured out cloud functions. Should have the full code in a day

**Comment by efawe** [comment]
Created the cloud function. How should I add some form of copy on the github?

**Comment by isaacmg** [comment]
@efawe Is it working on GCP? If so open a PR containing the code and the requirements.txt file. Store it a directory in the following way `cloud_functions/partition_county/main.py` and `cloud_functions/partition_county/requirements.txt`

**Comment by efawe** [comment]
Yes and will do

**Comment by efawe** [comment]
Created a separate issue that is more reflective of the development. Currently google cloud functions is not practical financially. 
#69 #
